blocks:
  - name: Step1
    step:
      integration: python
      python:
        body:
          path: ./step1.py
metadata:
  id: 1843acb2-9ad8-404c-a521-e4d432ccc124
  name: API1
  organization: 36867ce5-928a-44d0-baae-5379d235846d
trigger:
  application:
    id: 75107ea0-c7ad-4dca-a966-19a2d8020801
    pageId: e4277e59-0dfd-4d16-a129-9dbc75399ae1
