"""add logs_cache to deployments

Revision ID: 5e46f25b5c13
Revises: 52220b6cc03a
Create Date: 2026-06-08 20:54:46.370528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e46f25b5c13'
down_revision: Union[str, None] = '52220b6cc03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('logs_cache', sa.String(length=65535), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'logs_cache')
    # ### end Alembic commands ###
