apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespaces.apps }}-quota
  namespace: {{ .Values.namespaces.apps }}
  labels:
    {{- include "gatekeeperai.labels" . | nindent 4 }}
spec:
  hard:
    pods: "50"
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "25"
    limits.memory: 50Gi
    count/services: "50"
    count/secrets: "100"
