apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatekeeperai.fullname" . }}-frontend
  labels:
    {{- include "gatekeeperai.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "gatekeeperai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
