apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatekeeperai.fullname" . }}-authorized-keys
  labels:
    {{- include "gatekeeperai.labels" . | nindent 4 }}
data:
  authorized_keys: |
    {{ .Values.git.authorizedKeys | default "" | nindent 4 | trim }}
