apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.apps }}
  labels:
    managed-by: gatekeeperai
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.builds }}
  labels:
    managed-by: gatekeeperai
