{{- if gt (int .Values.replicas.api) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gatekeeperai.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatekeeperai.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "gatekeeperai.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
---
{{- if gt (int .Values.replicas.frontend) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gatekeeperai.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatekeeperai.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "gatekeeperai.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
